name: on-issue-event
on:
  issues:
    types: [opened, edited]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for opening or editing a Hazard in the RCPCH dGC Hazard Log.
            ### Next steps
            * Please use the [Labels](https://github.com/rcpch/digital-growth-charts-hazard-log/labels) feature in the right sidebar area to stratify this Hazard in terms of **Likelihood** and **Severity**
